# Vectors, Matrices, And Arrays

# Create A Vector

In [1]:
#Load Library
import numpy as np

In [2]:
# Create a vector as a row
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [3]:
# Create a vector as a column
vector_column = np.array([[1],
                         [2],
                         [3]])
vector_column

array([[1],
       [2],
       [3]])

# Create A Matrix

In [4]:
matrix = np.array([[1,4],
                  [2,5]])
matrix

array([[1, 4],
       [2, 5]])

# Create A Sparse Matrix

In [5]:
import numpy as np
from scipy import sparse

In [6]:
# Create  a matrix
matrix = np.array([[0,0],
                  [0,1],
                  [0,3]])

In [7]:
# Convert to Sparse Matrix
matrix_sparse = sparse.csc_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Column format>

# Transpose A Vector Or Matrix

In [8]:
# Create a vector
vector = np.array([1,2,3,4,5,6])
vector

array([1, 2, 3, 4, 5, 6])

In [9]:
# Transpose a vector
vector.T

array([1, 2, 3, 4, 5, 6])

In [10]:
# Create a Matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,5,6]])

In [11]:
# Transpose a Matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 5],
       [3, 6, 6]])

In [12]:
# Calculate Dot Product of Two Vectors
import numpy as np
# Create Two Vector
vector_a = np.array([1,2,3])
vector_b = np.array([5,6,8])


In [13]:
method_1 = np.dot(vector_a,vector_b)    # Method 1
method_2 = vector_a @ vector_b          # Method 2
print(f"Method 1 \t{method_1}\t Output")
print(f"Method 2 \t{method_2}\t Output")

Method 1 	41	 Output
Method 2 	41	 Output


# Selecting Elements In An Array.

In [14]:
# Create a row Vector
vector = np.array([1,2,3,4,5,6])    # index start from  0 
# Select the 3rd Elements
vector[2]

3

In [15]:
# Create a Matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [8,5,9]])
# Select second row,second column
matrix[1,1]

5

In [16]:
# Create a tensor
# Create matrix
tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])

In [17]:
# Select second element of each of the three dimensions
tensor[1,1,1]

array([4, 4])

# Reshape An Array

In [18]:
# Create a 4*3 matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,111,12]])

In [19]:
# Reshape a matrix into 2*6 matrix
matrix.reshape(2,6)

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10, 111,  12]])

# Invert A Matrix

In [20]:
import numpy as np
# Create a matrix
matrix =np.array([[1,4],
                [2,5]])


In [21]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# Getting The Diagonal Of A Matrix

In [22]:
import numpy as np                                        # [* 0 0
# Create a Matrix                                            0 * 0
matrix = np.array([[1,2,3],                               #  0 0 * ]
                 [4,5,6],
                 [7,8,9]])

In [23]:
# Return a Diagonal
matrix.diagonal()

array([1, 5, 9])

In [24]:
# calculate the tracre of the matrix
matrix.diagonal().sum()

15

# Flatten A Matrix

In [25]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [26]:
# Flatten  matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find The Rank Of A Matrix

In [27]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

# Find The Maximum And Minimum

In [28]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
# Return  maximum element
np.max(matrix)

9

In [30]:
# Return Minimum element
np.min(matrix)

1

In [31]:
# Find the maximum element in each column
np.max(matrix,axis = 0)

array([7, 8, 9])

In [32]:
# Find the minimum element in each row
np.min(matrix,axis = 1)

array([1, 4, 7])

# Describe An Array

In [33]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [34]:
# view number of rows and columns
matrix.shape

(3, 4)

In [35]:
# View total elements
matrix.size

12

In [36]:
# View number od dimensions
matrix.ndim

2

# Converting A Dictionary Into A Matrix

In [37]:
from sklearn.feature_extraction import DictVectorizer

In [38]:
# Our dictionary of data
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

In [39]:
# Create a DictVectorizer object
dictvectorizer = DictVectorizer(sparse =False)
# Convert dictionary into feature matrix
features = dictvectorizer.fit_transform(data_dict)
# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [40]:
# View columns names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']

# Calculate The Determinant Of A Matrix

In [41]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [42]:
# Return determinant of matrix
np.linalg.det(matrix)

-9.51619735392994e-16

# Calculate The Average, Variance, And Standard Deviation

In [43]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [44]:
# Return Mean
np.mean(matrix)

5.0

In [45]:
# Return variance
np.var(matrix)

6.666666666666667

In [46]:
# Return standard deviation
np.std(matrix)

2.581988897471611

# Apply  Operations to elements


In [47]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [48]:
# Create a vectorized function
add_100 = lambda i :i+100
# Create  a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [49]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Adding And Subtracting Matrice

In [50]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [51]:
# Add
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [52]:
# Subtract
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])